name: Run a bundle exec command

on:
  workflow_call:
    inputs:
      command:
        description: The command to run
        required: true
        type: string
      label:
        description: A label for the job
        required: true
        type: string
      ruby-version:
        description: The Ruby version to use
        required: true
        type: string
      setup:
        description: Run bin/setup before the command
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  run:
    name: Run
    runs-on: ubuntu-24.04

    steps:
      - name: Clone Pennycress
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install Ruby
        uses: ruby/setup-ruby@14594264cd68ce8a2345dd349bc3d138a4ef85c8 # v1
        with:
          ruby-version: ${{ inputs.ruby-version }}
          bundler-cache: true

      - name: Set up Pennycress
        if: inputs.setup
        run: bin/setup

      - name: ${{ inputs.label }}
        run: bundle exec ${{ inputs.command }}
